name: Databricks Dashboards CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allow manual trigger

jobs:
  validate_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Validate Bundle (Dev)
        run: |
          databricks bundle validate --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID_DEV }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: validate_dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Deploy to Dev
        run: |
          databricks bundle deploy --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID_DEV }}

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Deploy to Prod
        run: |
          databricks bundle deploy --target prod
        env:
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID_PROD }}
