name: Deploy Dashboards Dev → Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_SP_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python & CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Deploy Dashboards to Prod
        run: |
          for file in dashboards/*.lvdash.json; do
            filename=$(basename $file)
            echo "Deploying $filename to Prod Workspace"
            databricks workspace import $file /Dashboards/$filename --format DASHBOARD --overwrite
          done
