name: Deploy Dashboards Dev → Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_SP_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy Dashboards to Prod
        run: |
          for file in *.lvdash.json; do
            filename=$(basename "$file")
            echo "Deploying $filename to Prod Workspace"
            curl -s -X POST "$DATABRICKS_HOST/api/2.0/preview/sql/dashboards/import" \
              -H "Authorization: Bearer $DATABRICKS_TOKEN" \
              -F "file=@$file" \
              -F "overwrite=true"
            echo "$filename deployed successfully."
          done
